### PR TITLE
cleaned up github action.

### PR DESCRIPTION
**Pull request by simsong**
Not sure why we want to run make check wit and without address sanitizer.
Perhaps @uckelman-sf  knows?

### CODE REVIEW

**Comment by simsong** [comment]
yay! it works.

**Comment by uckelman-sf** [comment]
We want to run both ways because they could have different behavior.

**Comment by simsong** [comment]
> We want to run both ways because they could have different behavior.

Really? I've never seen that.

**Comment by uckelman-sf** [comment]
You won't ever see it if you don't run both.

Each has a reason to be run: The sanitizer build finds bugs. The non-sanitizer build is a production build, which is exactly the thing we want to pass the tests.

**Pull request merged**
