### PR TITLE
APFS and Pooled Storage Support

### PR DESCRIPTION
**Pull request by jtsylve**
This (rather large) PR adds a pooled storage layer and APFS file system support to libtsk.

It adds a new dependency on openssl, and since the implementation is mostly in C++14, MSVC 2015, gcc-5, or clang 3.4 or later is needed.

More info:
https://www.youtube.com/watch?v=k1XPillJ7aw
https://youtu.be/XozHCaTzY0c?t=1337

### CODE REVIEW

**Comment by jtsylve** [comment]
FWIW, I'm not getting these errors on my local up-to-date version of Visual Studio Community 2015 (Version 14.0.25431.01 Update 3).  Still trying to address them, but updating the builder might resolve them.

**Comment by jtsylve** [comment]
I changed the following in the CI scripts, so that now the checks are passing:
- Changed the versions of the libyal tools to the latest release (old release no longer existed)
- Changed travis distro to xenial (because gcc-5 is default and gcc-4 doesn't have full C++14 support)
- Added openssl dependencies

Let me know if any of this should be a separate PR.

**Comment by lfcnassif** [comment]
Thank you very much for this great work! Any plans to integrate this functionality into tsk_loaddb and java bindings implementation?

**Comment by jtsylve** [comment]
Not by me as we don't use that functionality.  Someone else would have to tackle Javaland.

**Comment by lfcnassif** [comment]
Thanks @jtsylve. When I have time I will take a look and try to contribute some code if I can get it to work locally.

**Comment by lfcnassif** [comment]
Hi @jtsylve. I coded some hacks to make tsk_loaddb and libtsk_jni work with your APFS implementation. It is working for allocated files. For unallocated, I received the msg:

"Function/Feature not supported (block_walk not implemented for APFS yet) (TskAutoDb::addFsInfoUnalloc: error walking fs unalloc blocks, fs id: 1851011)".

I do not know APFS details. Each APFS FS contains unalloc blocks or those blocks belongs to container pool? Is it possible to walk unalloc blocks of container pool?

Thanks

**Comment by rcordovano** [comment]
@jtsylve, as the next step to integrating this work into main line TSK, I have created an apfs feature branch from the current develop branch, and re-targeted the PR to the apfs branch. If you would kindly resolve the merge conflicts, I will accept the PR into apfs, where @APriestman can do some additional integration work, and then we will merge the apfs branch into develop. Thanks!

**Comment by rcordovano** [comment]
@jtsylve, alternatively, @APriestman can take it from here...

**Comment by rcordovano** [comment]
@jtsylve, we will proceed with @APriestman resolving the merge conflicts in this PR by merging this PR into the apfs feature branch, at which point we will close this PR. Thanks!

**Comment by APriestman** [comment]
@lfcnassif If you'd like, you could make a PR with your tsk_loaddb and jni code to the apfs branch. Those are things we'd like to get working.

**Comment by lfcnassif** [comment]
Hello @APriestman  my implementation of jni side was very hacky because of time constraints, and currently I do not have time to make it better. Probably its current quality is not acceptable to be merged.
I can tell you I had some problems with thread safety and needed to synchronize access to metadata of apfs files. No need to synchronize access to file contents from multiple threads, fortunatelly, as it could make file reading very slow.

**Pull request merged**
