### PR TITLE
update sqlite version

### PR DESCRIPTION
**Pull request by gdicristofaro**

### CODE REVIEW

**Comment by jayaramcs** [comment]
@simsong would you like me to go ahead with merge or do you want to look over once?

**Comment by simsong** [comment]
> @simsong would you like me to go ahead with merge or do you want to look over once?

I usually wait for all of the checks to pass. This time AppVeyor failed for a really weird reason:
https://ci.appveyor.com/project/bcarrier/sleuthkit/builds/51102566/job/sud76q1mdhfc1yjf
image

Do you know what's wrong with the appveyor system? WHere does it run? Are the VMs clean on each run? Why are we having so many problems with it?

Thanks.

**Comment by jayaramcs** [comment]
i can take a look. it is supposed to use clean VMs. no idea why it has problems.

**Comment by jayaramcs** [comment]
@simsong This [commit](https://github.com/sleuthkit/sleuthkit/commit/d071536e5110f26569ee8c894e49897a451d40eb) on develop fixes the issue. I can make the change to this branch manually, but it is likely going to cause merge conflicts if I do so. 
The main issue seems to be that aclocal is not on the appveyor environment. Since develop has stopped using it from what I can tell, I am not inclined to fixing the appveyor system only for this one branch.

**Comment by simsong** [comment]
Sometimes simply pulsing the AppVeyor a second time fixes the problem. I've seen it being very finicky. I'm going to update this branch and see what happens.

**Pull request merged**
