### PR TITLE
5469 Add APFS support to more TSK tools

### PR DESCRIPTION
**Pull request by APriestman**

### CODE REVIEW

**Comment by rcordovano** [comment]
@APriestman, is the lone Codacy issue something we can resolve?

**Comment by APriestman** [comment]
I'd rather keep all the declarations in one spot.

**Comment by lfcnassif** [comment]
Hello devs, thank you for your work. Do you have plans to implement APFS support in tsk_loaddb?

**Comment by APriestman** [comment]
Is it not working for you? I believe we added it to tsk_loaddb in the last
release, and it's definitely in the current develop code.

**Comment by lfcnassif** [comment]
Hi Ann, I can't see any apfs option or code in tsk_loaddb.cpp in 4.8.0 tag, neither in de develop branch. Or am I missing something?

**Comment by APriestman** [comment]
You shouldn't need APFS options for tsk_loaddb. Like tsk_gettimes, it iterates over all volumes and pools and files systems in the image. The changes to make it work were over in auto.cpp and auto_db.cpp. For example, I have an image with four APFS volumes. I need the pool block to run fls:
$ ./fls.exe -B 6835 apfs_four_vols.dd
d/d 16: .Spotlight-V100
r/r 207:        vol1.txt
d/d 208:        vol1 folder
d/d 20: .Trashes
d/d 22: .fseventsd
r/r 206:        giraffe1.jpg

But tsk_loaddb iterates over all the APFS volumes in the pool, so I can run it with no options.
$ ./tsk_loaddb.exe apfs_four_vols.dd
Database stored at: apfs_four_vols.dd.db

Files from all four APFS volumes end up in the database.

**Comment by lfcnassif** [comment]
Got it Ann, thank you. But I think at least an option for the password is needed, or it is passed through a different way?

**Comment by APriestman** [comment]
Encryption is not currently supported for any APFS tools. We were unable to get the libraries working well with our automated builds.

**Comment by lfcnassif** [comment]
Thank you, Ann! Sorry for not testing before. Release notes confused me about encryption.

**Pull request merged**
