### PR TITLE
added CXX=clang++

### PR DESCRIPTION
**Pull request by simsong**
Per #3013

### CODE REVIEW

**Comment by simsong** [comment]
tagging @joachimmetz and @uckelman-sf

**Comment by joachimmetz** [comment]
LGTM, I meant you can also directly edit my feature branch. But I see that github did not enable this by default

I've turned on `Allow edits and access to secrets by maintainers`

**Comment by simsong** [comment]
Okay. How do we get clang++ to support C++14?
```
checking how to hardcode library paths into programs... unsupported
checking whether clag++ supports C++14 features with -std=c++14... no
checking whether clag++ supports C++14 features with +std=c++14... no
checking whether clag++ supports C++14 features with -h std=c++14... no
checking whether clag++ supports C++14 features with -std:c++14... no
checking whether clag++ supports C++14 features with -std=c++1y... no
checking whether clag++ supports C++14 features with +std=c++1y... no
checking whether clag++ supports C++14 features with -h std=c++1y... no
checking whether clag++ supports C++14 features with -std:c++1y... no
configure: error: *** A compiler with support for C++14 language features is required.
Error: Process completed with exit code 1.
```

**Comment by joachimmetz** [comment]
Per https://clang.llvm.org/cxx_status.html looks like you can set it with `-std=c++14`

**Comment by joachimmetz** [comment]
but there is a typo, shouldn't it be clang with an n ?

**Comment by simsong** [comment]
Oh, okay. Yes, that's me, Dr. Typo.

**Comment by simsong** [comment]
> LGTM, I meant you can also directly edit my feature branch, but I see that github did not enable this by default
> 
> I've turned on `Allow edits and access to secrets by maintainers`
> 
> to be explicit, I cannot merge or approve this PR in Github

I'm confused what this means...?

**Comment by joachimmetz** [comment]
> I'm confused what this means...?

In github as a maintainer (when `Allow edits and access to secrets by maintainers` is enabled) you can directly make changes to the feature branch linked to the PR, e.g. https://github.com/joachimmetz/sleuthkit/tree/clang 

This allows you as a maintainer to directly make changes instead of having many round trips over comments.

also see: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork and https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by simsong** [comment]
Huh. I can’t figure out where that is. Sorry!

**Pull request merged**
