### PR TITLE
Replace deprecated OpenSSL AES functions

### PR DESCRIPTION
**Pull request by uckelman-sf**
This PR replaces the `AES_*` functions deprecated as of OpenSSL 3.0 with current equivalents using the `EVP_*` functions. A test of `rfc3394_key_unwrap()` is provided, which passes before and after the change.

### CODE REVIEW

**Comment by uckelman-sf** [comment]
Closes Issue #3047.

**Comment by uckelman-sf** [comment]
@simsong Something went wrong with installing a Python package with the AppVeyor build. Is there some way to give it a kick so it will run again?

**Comment by simsong** [comment]
Sure. We just make a minor change to the PR. That's all I can do.

**Comment by simsong** [comment]
Actually, I think that you need to do it.

**Comment by uckelman-sf** [comment]
I can always force push to the PR to trigger a build. I thought there might have been some button you have for AppVeyor, though, so as not to rerun everything. Guess not.

**Comment by simsong** [comment]
> I can always force push to the PR to trigger a build. I thought there might have been some button you have for AppVeyor, though, so as not to rerun everything. Guess not.

I have a button like that for GitHub Actions, but not for AppVeyor.

**Comment by uckelman-sf** [comment]
This appears to be the failure from AppVeyor:
```  Complete output from command /home/appveyor/projects/sleuthkit/tests/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-h4bass7k/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp8hea7mq1pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for PyYAML
  Running setup.py clean for PyYAML
Failed to build PyYAML
```
This doesn't look related to my changes.

**Comment by simsong** [comment]
Is it running in other branches? Perhaps @jayaramcs can shed some light. I have no visibility into AppVeyor.

**Comment by simsong** [comment]
If I don't hear from @jayaramcs , I'll close this later today.

**Comment by uckelman-sf** [comment]
AppVeyor was running on this branch on Friday. (What I was doing on Friday was trying to determine why AppVeyor builds were running but failing.) AppVeyor is running for #3050 right now.

**Comment by simsong** [comment]
> @simsong This is ready for review now.
> 
> The problem with AppVeyor builds failing was that it has a fairly old version of Ubuntu which has OpenSSL 1.1, which I eventually accommodated but wasn't obvious at first that it was causing a problem.

I was concerned about forcing everyone to use SSL 3.0.

**Pull request merged**
