### PR TITLE
Cppunit cleanup

### PR DESCRIPTION
**Pull request by uckelman-sf**
Usage of cppunit is broken at present. These changes make it functional for testing once again.

### CODE REVIEW

**Comment by bcarrier** [comment]
@uckelman-sf : Can you define the "Broken" you were trying to fix?  I just realized on my mac that TSK doesn't find 'cppunit' that I install via homebrew, but this PR doesn't fix that either.  Does this PR fix an issue with finding cppunit, a compiler error, or something else?

**Comment by uckelman-sf** [comment]
There are several problems. 

The define for having cppunit is misnamed---the convention is that it should be called `HAVE_CPPUNIT`, not `CPPUNIT`. The flags gotten for cppunit from running `configure` aren't preprocessor flags so shouldn't go into `CPPFLAGS` for compiling the tests. That breaks compilation for me. Moving them into `CXXFLAGS` where they belong fixes that. `runner.cpp` is missing from the test sources which prevents the tests from linking.

**Comment by uckelman-sf** [comment]
Hello? This PR has been open for more than a year. Would you review it, please?

**Comment by uckelman-sf** [comment]
Fixed conflicts again.

**Comment by uckelman-sf** [comment]
> @uckelman-sf : I just realized on my mac that TSK doesn't find 'cppunit' that I install via homebrew, but this PR doesn't fix that either.

Can you tell me where cppunit is installed by homebrew? What you might need is `--with-cppunit-prefix=/path/to/cppunit` as an argument to `./configure`.

**Comment by uckelman-sf** [comment]
Hello? What's the status on getting this PR merged?

**Comment by uckelman-sf** [comment]
Closing in favor of PR #2942.

**Pull request closed without merging**
