### PR TITLE
Remove unused travis config

### PR DESCRIPTION
**Pull request by uckelman-sf**
Completes Issue #2471.

### CODE REVIEW

**Comment by uckelman-sf** [comment]
@simsong Ready for review.

**Comment by simsong** [comment]
nobody is using Travis?

**Comment by simsong** [comment]
(We say Closes instead of Completes so the issue gets closed automatically when we merge the pull request.)

**Comment by uckelman-sf** [comment]
> (We say Closes instead of Completes so the issue gets closed automatically when we merge the pull request.)

The ones where I said closes haven't been closing issues automatically.

**Comment by simsong** [comment]
> > (We say Closes instead of Completes so the issue gets closed automatically when we merge the pull request.)
> 
> The ones where I said closes haven't been closing issues automatically.

Weird. When I checked it to `Closes` and then accepted the PRs, they closed!

**Pull request merged**
