### PR TITLE
Fix source file permissions

### PR DESCRIPTION
**Pull request by uckelman-sf**
chmod a-x all of the C/C++ source files and headers.

### CODE REVIEW

**Comment by simsong** [comment]
Hi. Thanks for contributing this. However, the appveyor build fails:
https://ci.appveyor.com/project/bcarrier/sleuthkit/builds/50461252/job/haljfwcfteabm972
image
Can you fix this?

**Comment by uckelman-sf** [comment]
Maybe, but it's not related to this PR. Let me see...

**Comment by simsong** [comment]
> It looks like all Linux CI builds are failing due to this.

Is this something you can fix? 
My goal is to start adding GitHub actions as I find them easier to work with than AppVeyor, but there is no reason that we can't use both.

**Comment by simsong** [comment]
> Maybe, but it's not related to this PR. Let me see...

True, but I like having clean builds before accepting PRs!

**Comment by uckelman-sf** [comment]
I was going to suggest moving to GitHub Actions, as I've had good experience with them in the past. They're also _much_ faster to start than appveyor. I'm still waiting for the job to run to see if my change worked...

**Comment by simsong** [comment]
> I was going to suggest moving to GitHub Actions, as I've had good experience with them in the past. They're also _much_ faster to start than appveyor. I'm still waiting for the job to run to see if my change worked...

My plan is to run them in parallel.

**Comment by uckelman-sf** [comment]
There we go. The test runner didn't have autoconf installed. It works now.

**Comment by simsong** [comment]
Yay! Let's see if I can make this happen now...

**Comment by uckelman-sf** [comment]
Woo! Thanks!

**Comment by uckelman-sf** [comment]
@simsong Next one is here: PR 2942.

**Pull request merged**
