### PR TITLE
Numerous LVM support improvements

### PR DESCRIPTION
**Pull request by joachimmetz**
Includes numerous changes contributed by arisjr@

### CODE REVIEW

**Comment by simsong** [comment]
Hi @joachimmetz  - do you have test media that validates these patches?

**Comment by joachimmetz** [comment]
There are several mentioned in https://github.com/sleuthkit/autopsy/issues/7888 and you can create some with https://github.com/dfirlabs/lvm-specimens

**Comment by simsong** [comment]
> https://github.com/dfirlabs/lvm-specimens

I'm collecting the test media at digitalcorpora.org; if you think that there is a better place to put them, please let me know. I'm hesitant to use github because they charge for I/O downloads from their large object support.

**Comment by lfcnassif** [comment]
Hi @arisjr and @joachimmetz. Any specific reason why commit [2fa3241](https://github.com/sleuthkit/sleuthkit/pull/2820/commits/2fa3241ec99af7b7f41daeab545468e8b1cf08bb) reverted the change of #2702 or was it by accident???

**Comment by joachimmetz** [comment]
@lfcnassif what is https://github.com/sleuthkit/sleuthkit/pull/2702 ? First time I hear of it. How is a change in the common code supposed to address an APFS specific issue https://github.com/sleuthkit/sleuthkit/issues/2700 ?

My guess it was not intentional "reverted" but overlooked in merge/review.

**Comment by joachimmetz** [comment]
> I'm collecting the test media at digitalcorpora.org; if you think that there is a better place to put them, please let me know. I'm hesitant to use github because they charge for I/O downloads from their large object support.

@simsong the goal of lvm-specimens is make reproducible test images with different versions of LVM implementations (broad set of format cases and features), not to provide a collection of (narrowly scoped) pre-generated test images.

**Comment by simsong** [comment]
That's great. I'm fine if we can make reproducible test images without having to archive the bits.

**Comment by lfcnassif** [comment]
> @lfcnassif what is #2702 ? First time I hear of it. How is a change in the common code supposed to address an APFS specific issue #2700 ?

Hi @joachimmetz. Maybe it is not specific to APFS, but it showed up in a real case APFS image. If TSK fails to decode a specific volume, shouldn't it try to decode the next volumes in the same image instead of aborting?

**Comment by lfcnassif** [comment]
> I'm talking to @arisjr to know if it was intentional or not.

@arisjr confirmed it wasn't intentional.

**Pull request merged**
