### PR TITLE
Maximum of partitions with GPT is not 128, so slot_num can't be int8_t

### PR DESCRIPTION
**Pull request by aapo**
GPT partition table can be tuned to have maximum of 65536 partitions. Therefore slot_num must be int_16t

Testing: 

    dd if=/dev/zero of=disk.dd bs=2M count=100
    echo 'label: gpt' | sfdisk disk.dd
    
    #gdisk: change to expert_mode+resize partition table+max partitions=256+write+yes
    echo -e "x\ns\n256\nw\ny\n" | gdisk disk.dd 
    
    
    for i in {0..130}
    do
    echo "size=2048, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4" | sfdisk --quiet --append disk.dd
    done

Now at least mmls shows funny slot_numbers:

    mmls disk.dd | tail
    126:  122       0000251904   0000253951   0000002048   
    127:  123       0000253952   0000255999   0000002048   
    128:  124       0000256000   0000258047   0000002048   
    129:  125       0000258048   0000260095   0000002048   
    130:  126       0000260096   0000262143   0000002048   
    131:  127       0000262144   0000264191   0000002048   
    132:  4294967168       0000264192   0000266239   0000002048   
    133:  4294967169       0000266240   0000268287   0000002048   
    134:  4294967170       0000268288   0000270335   0000002048   
    135:  -------   0000270336   0000409599   0000139264   Unallocated

After patch:

    126:  122       0000251904   0000253951   0000002048   
    127:  123       0000253952   0000255999   0000002048   
    128:  124       0000256000   0000258047   0000002048   
    129:  125       0000258048   0000260095   0000002048   
    130:  126       0000260096   0000262143   0000002048   
    131:  127       0000262144   0000264191   0000002048   
    132:  128       0000264192   0000266239   0000002048   
    133:  129       0000266240   0000268287   0000002048   
    134:  130       0000268288   0000270335   0000002048   
    135:  -------   0000270336   0000409599   0000139264   Unallocated

### CODE REVIEW

**Comment by bcarrier** [comment]
Hi @aapo.  I took a quick look at this. The PNUM_T type is already defined as 32-bits.  I think the proper solution is to just use PNUM_T for the 'slot' number. Would you agree?  

It seems reasonable that there would be as many slots as there are partitions.

**Comment by aapo** [comment]
https://github.com/sleuthkit/sleuthkit/blob/develop/tsk/base/tsk_base.h#L267

    tsk/base/tsk_base.h:267:    typedef uint32_t TSK_PNUM_T;        ///< Data type used to internally store partition addresses

I don't get how name and comment correlate (PNUM and partition address). And it is way bigger than needed. Maximum number of partitions in GPT is 0xffff = 65535.

**Comment by simsong** [comment]
> https://github.com/sleuthkit/sleuthkit/blob/develop/tsk/base/tsk_base.h#L267
> 
> ```
> tsk/base/tsk_base.h:267:    typedef uint32_t TSK_PNUM_T;        ///< Data type used to internally store partition addresses
> ```
> 
> I don't get how name and comment correlate (PNUM and partition address). And it is way bigger than needed. Maximum number of partitions in GPT is 0xffff = 65535.

I think that @bcarrier would rather use `PNUM_T` than `int16_t` because `PNUM_T` is used elsewhere in the code base for a partition number.

**Comment by simsong** [comment]
Oddly, this is not a problem on MacOS systems, only on Linux systems:
```
simsong@Simsons-MacBook-Pro sleuthkit % mmls -V
The Sleuth Kit ver 4.12.1
simsong@Simsons-MacBook-Pro sleuthkit % mmls disk.dd | tail
126:  122       0000251904   0000253951   0000002048
127:  123       0000253952   0000255999   0000002048
128:  124       0000256000   0000258047   0000002048
129:  125       0000258048   0000260095   0000002048
130:  126       0000260096   0000262143   0000002048
131:  127       0000262144   0000264191   0000002048
132:  128       0000264192   0000266239   0000002048
133:  129       0000266240   0000268287   0000002048
134:  130       0000268288   0000270335   0000002048
135:  -------   0000270336   0000409599   0000139264   Unallocated
simsong@Simsons-MacBook-Pro sleuthkit %
```
And I have an Ubuntu 24.04 system here:
```
simsong@dell4:~$ mmls -V
The Sleuth Kit ver 4.12.1
simsong@dell4:~$ mmls disk.dd | tail
126:  122       0000251904   0000253951   0000002048
127:  123       0000253952   0000255999   0000002048
128:  124       0000256000   0000258047   0000002048
129:  125       0000258048   0000260095   0000002048
130:  126       0000260096   0000262143   0000002048
131:  127       0000262144   0000264191   0000002048
132:  4294967168       0000264192   0000266239   0000002048
133:  4294967169       0000266240   0000268287   0000002048
134:  4294967170       0000268288   0000270335   0000002048
135:  -------   0000270336   0000409599   0000139264   Unallocated
```

**Comment by simsong** [comment]
> > https://github.com/sleuthkit/sleuthkit/blob/develop/tsk/base/tsk_base.h#L267
> > ```
> > tsk/base/tsk_base.h:267:    typedef uint32_t TSK_PNUM_T;        ///< Data type used to internally store partition addresses
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't get how name and comment correlate (PNUM and partition address). And it is way bigger than needed. Maximum number of partitions in GPT is 0xffff = 65535.
> 
> I think that @bcarrier would rather use `TSK_PNUM_T` than `int16_t` because `TSK_PNUM_T` is used elsewhere in the code base for a partition number.

The problem is, this:
```
tools/vstools/mmls.cpp: In function ‘TSK_WALK_RET_ENUM part_act(TSK_VS_INFO*, const TSK_VS_PART_INFO*, void*)’:
tools/vstools/mmls.cpp:63:57: error: comparison of integer expressions of different signedness: ‘const TSK_PNUM_T’ {aka ‘const unsigned int’} and ‘int’ [-Werror=sign-compare]
   63 |     else if ((part->table_num == -1) && (part->slot_num == -1))
      |                                          ~~~~~~~~~~~~~~~^~~~~
tools/vstools/mmls.cpp:67:57: error: comparison of integer expressions of different signedness: ‘const TSK_PNUM_T’ {aka ‘const unsigned int’} and ‘int’ [-Werror=sign-compare]
   67 |     else if ((part->table_num == -1) && (part->slot_num != -1))
      |                                          ~~~~~~~~~~~~~~~^~~~~
tools/vstools/mmls.cpp:72:57: error: comparison of integer expressions of different signedness: ‘const TSK_PNUM_T’ {aka ‘const unsigned int’} and ‘int’ [-Werror=sign-compare]
   72 |     else if ((part->table_num != -1) && (part->slot_num == -1))
      |                                          ~~~~~~~~~~~~~~~^~~~~
tools/vstools/mmls.cpp:76:57: error: comparison of integer expressions of different signedness: ‘const TSK_PNUM_T’ {aka ‘const unsigned int’} and ‘int’ [-Werror=sign-compare]
   76 |     else if ((part->table_num != -1) && (part->slot_num != -1))
      |                                          ~~~~~~~~~~~~~~~^~~~~
```

**Pull request merged**
