### PR TITLE
Codecov adjustments

### PR DESCRIPTION
**Pull request by uckelman-sf**
Exclude `test/`, `vendors/` from coverage analysis.

### CODE REVIEW

**Comment by uckelman-sf** [comment]
@simsong How do I check if this is working?

**Comment by simsong** [comment]
> @simsong How do I check if this is working?

It's not, but now I know why:
Google Chrome 2024-11-07 07 27 49

Google Chrome 2024-11-07 07 28 12

It appears that you do not have access to the `CODECOV_TOKEN` because it is a repository secret and you don't get access to those secrets when you run.   It's once supposed to need the secrets for an upload from an open source repository, but this seems to have changed...

https://github.com/codecov/codecov-action/issues/1255
"Yes, the release notes contradict GitHubs documentation."

I'll look into this later today.  As a short-term fix, you could try adding codecov to your personal repo.

https://docs.codecov.com/docs/adding-the-codecov-token#:~:text=The%20Codecov%20token%20must%20be,repository%20in%20Codecov%2C%20under%20General.

https://docs.codecov.com/docs/frequently-asked-questions

**Comment by uckelman-sf** [comment]
Maybe someone could cherry-pick the two commits here into a branch were codecov does have access to the secrets.

**Comment by simsong** [comment]
> Maybe someone could cherry-pick the two commits here into a branch were codecov does have access to the secrets.

What do you want me to do?

**Comment by uckelman-sf** [comment]
Nothing, now that this is merged and we can see the result in codecov. `tsk` and `tools` only are showing up in the results, which is the desired result.

**Pull request merged**
