### PR TITLE
Improved detection of image file split patterns

### PR DESCRIPTION
**Pull request by uckelman-sf**
Implemented detection of arbitrary-width alphabetic and zero-padded numeric image split patterns. (E.g., .00001 and .aaaa are now detected properly.) Includes a battery of split pattern detection tests.

Some imaging tools, such as MacQuisition, have started using five-digit split patterns. This patch lets Sleuthkit handle those in a way which is future-proof.

Also fixes Cppunit detection.

### CODE REVIEW

**Comment by sf-jonstewart** [comment]
@uckelman-sf can you check out the `configure.ac` conflict and the travis problem?

@bcarrier It would be _really helpful_ for there to be some public overview dev documentation about all of the new Travis/Codacy/AppVeyor stuff, and it would be helpful to know release timelines/roadmaps so we can target the correct base branches -- new TSK releases often come as a surprise, which means we must maintain our patch sets longer -- and to get outside PRs reviewed in similar fashion/timeframe to Basis PRs.

**Comment by jonstewart** [comment]
*bump*

**Comment by uckelman-sf** [comment]
Hello? This has been open since _2017_. Could we please get some eyes on this to get it merged? It fixes a bug and adds tests demonstrating that the bug is fixed.

**Comment by uckelman-sf** [comment]
Fixed conflicts again.

**Comment by uckelman-sf** [comment]
Fixed conflicts _again_.

**Comment by uckelman-sf** [comment]
@simsong This PR is ready for review.

**Pull request merged**
