### PR TITLE
Fix several NTFS decompression bugs (II)

### PR DESCRIPTION
**Pull request by uckelman-sf**
This PR fixes decompression errors in NTFS compressed files that have an initialized size which differs from the logical size, and also allows decompression of an NTFS compressed file to continue in the event that a  corrupted compression unit is encountered.

This PR includes the patches from PR #1183, and an additional patch for the remaining problem noted there.

### CODE REVIEW

**Comment by sf-jonstewart** [comment]
Howdy, @rcordovano, @bcarrier! We've got some nice clean NTFS decompression bug fixes waiting very patiently in this PR here...

**Comment by rcordovano** [comment]
Hi, @sf-jonstewart, thanks for the heads up. Someone on my team will review and test this PR if so directed by @bcarrier.

**Comment by jonstewart** [comment]
*bump*

Please apply this PR.

**Comment by jonstewart** [comment]
Reading NTFS Compressed files with TSK frequently generates errors. This PR seems to fix most (all?) of these errors.

**Comment by mat-gas** [comment]
_bump_ too for this PR

**Comment by uckelman-sf** [comment]
We've fixed the conflict. It would be great if this could be reviewed and merged, as this resolves a huge number of NTFS decompression errors.

**Comment by uckelman-sf** [comment]
We've had confirmation that this fixes issue #1792.

**Comment by jonstewart** [comment]
TSK's support for NTFS compression generates many errors on file reads—should be reproducible with just about any NTFS image.

Most (all?) of those errors are fixed with the following PR. It's been waiting here for three years.

**Pull request merged**
