### PR TITLE
AFF4 image read support

### PR DESCRIPTION
**Pull request by blschatz**
This patch adds AFF4 image read support to TSK.

### CODE REVIEW

**Comment by DexterHaslem** [comment]
Hi, just wanted to ping the status of this PR. It's waiting for the codacy issues to be fixed?

**Comment by blschatz** [comment]
Thanks for the prod. Will address and resolve.

**Comment by blschatz** [comment]
Fixed codacy PR blockers. The "errors" codacy was flagging were benign. Do you really prefer the "fix" I have just committed?

**Comment by DexterHaslem** [comment]
To be clear, I'm not affiliated with this repository. Just looking forward to AFF4 support in Autopsy, thanks!

**Comment by sf-jonstewart** [comment]
'twould be great to get this in... :+1:

**Comment by ydkhatri** [comment]
Been waiting on this for a long time, any ETA on this?

**Comment by uckelman-sf** [comment]
I've made some adjustments to this PR as #1272 to fix a few problems I found.

**Comment by bcarrier** [comment]
Is there a Windows library for AFF4?

**Comment by simsong** [comment]
Is this still relevant?

**Comment by uckelman-sf** [comment]
This PR is superceded by #1272 and can be closed.

**Pull request closed without merging**
