### PR TITLE
Changed fatfs_dos_2_unix_time to function time zone independent #2317

### PR DESCRIPTION
**Pull request by joachimmetz**

### CODE REVIEW

**Comment by joachimmetz** [comment]
@APriestman @rcordovano fix for issue https://github.com/sleuthkit/sleuthkit/issues/2317

**Comment by simsong** [comment]
Hi @joachimmetz  - If you can fix the AppVeyor error on this, I'll accept it.
https://ci.appveyor.com/project/bcarrier/sleuthkit/builds/49562600/job/ltydstavjmnvs4hu

**Comment by joachimmetz** [comment]
@simsong the CI test error is not related to the PR

```
    [javac] C:\projects\sleuthkit\bindings\java\test\org\sleuthkit\datamodel\PublicTagName.java:13: error: incompatible types: FileKnown cannot be converted to TagType
 ```

**Comment by simsong** [comment]
Indeed, and now the tests pass.

**Pull request merged**
