### PR TITLE
5284 better deal with out of space in logical imager

### PR DESCRIPTION
**Pull request by jkho**

### CODE REVIEW

**Comment by APriestman** [comment]
This seems to include a bunch of changes that were part of https://github.com/sleuthkit/sleuthkit/pull/1556 ?

**Comment by jkho** [comment]
I merged upstream/develop into this branch. But the common code (in both develop and this branch) remains in the PR. Not sure why.

**Comment by jkho** [comment]
I figured it out. [#1556](https://github.com/sleuthkit/sleuthkit/pull/1556/files) merges into release-4.6.7. But release-4.6.7 has not been merged into develop. @rcordovano

**Comment by jkho** [comment]
I think this PR has the minimal changes now.

**Comment by rcordovano** [comment]
@jkho, please resolve the merge conflicts. @APriestman, please approve or request additional changes. Thanks!

**Comment by APriestman** [comment]
See the Jira - Brian doesn't want the user to have to press a key in error cases if they chose not to prompt before exit.

**Comment by rcordovano** [comment]
Closing this PR because it does not auto-merge and additional work has been requested.

**Pull request closed without merging**
