### PR TITLE
Mark unused function parameters as unused

### PR DESCRIPTION
**Pull request by uckelman-sf**

### CODE REVIEW

**Review by simsong — COMMENTED** [review]
Is there a specific feature you want in C++17?

**Comment by uckelman-sf** [comment]
> Is there a specific feature you want in C++17?

Several, and it's on the way to C++20. In this particular case, I want `[[maybe_unused]]` annotations.

**Review by simsong — CHANGES_REQUESTED** [review]
This updates us to C++17 when compiling with autotools. We need to also update to C++17 when compiling on windows with the python program that calls the Microsoft compiler.

**Comment by simsong** [comment]
> > Is there a specific feature you want in C++17?
> 
> Several, and it's on the way to C++20. In this particular case, I want `[[maybe_unused]]` annotations.

Okay; why not just jump to C++20 directly?

**Comment by uckelman-sf** [comment]
I don't need C++20 for this. Going incrementally minimizes risk.

**Comment by uckelman-sf** [comment]
> This updates us to C++17 when compiling with autotools. We need to also update to C++17 when compiling on windows with the python program that calls the Microsoft compiler.

It seems to build on Windows without changes to the script. Otherwise: Do you have any idea how the script should be updated?

**Comment by uckelman-sf** [comment]
@simsong Ready for review.

**Review by simsong — APPROVED** [review]
A lot of changes, mostly changing from `.c` to `.cpp` and then adding a lot of ``[[maybe_unused]]`` annotations.

**Comment by simsong** [comment]
> A lot of changes, mostly changing from `.c` to `.cpp` and then adding a lot of `[[maybe_unused]]` annotations.
I'm concerned about this, because it's going to make it much, much harder to integrate the previous pull requests now.

**Comment by uckelman** [comment]
> I'm concerned about this, because it's going to make it much, much harder to integrate the previous pull requests now.

I don't believe it will. Rebasing will take care of filename changes.

**Comment by simsong** [comment]
> > I'm concerned about this, because it's going to make it much, much harder to integrate the previous pull requests now.
> 
> I don't believe it will. Rebasing will take care of filename changes.

I suppose you are right, but I typically avoid `git rebase`. I should get better with it. 
c.f. https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by uckelman** [comment]
The first thing I do when I work on a branch is rebase it over the current state of the branch it will be merged to. That helps minimize conflicts.

**Comment by simsong** [comment]
> The first thing I do when I work on a branch is rebase it over the current state of the branch it will be merged to. That helps minimize conflicts.

Ah. I typically merge with the branch that I eventually plan to merge into. So instead of doing a `git merge develop`  all I need to do is a `git rebase develop`, correct?

**Comment by uckelman** [comment]
Yep. That's what I do when I work on branches.

**Comment by simsong** [comment]
@uckelman — Well, I did that, and now I can't push. Suggestion?

simsong@Simsons-MacBook-Pro sleuthkit % git rebase develop
Successfully rebased and updated refs/heads/develop-btrfs.
simsong@Simsons-MacBook-Pro sleuthkit % git push origin
To github.com:sleuthkit/sleuthkit.git
 ! [rejected]            develop-btrfs -> develop-btrfs (non-fast-forward)
error: failed to push some refs to 'github.com:sleuthkit/sleuthkit.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
simsong@Simsons-MacBook-Pro sleuthkit % git pull
From .
 * branch                basicmaster/develop-btrfs -> FETCH_HEAD
Already up to date.
simsong@Simsons-MacBook-Pro sleuthkit % git push origin
To github.com:sleuthkit/sleuthkit.git
 ! [rejected]            develop-btrfs -> develop-btrfs (non-fast-forward)
error: failed to push some refs to 'github.com:sleuthkit/sleuthkit.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
simsong@Simsons-MacBook-Pro sleuthkit %
```

Any suggestions?

**Comment by simsong** [comment]
I guess a force push does it.

**Comment by uckelman** [comment]
You have to force push after rebasing.

**Comment by simsong** [comment]
I discovered. Ick.

**Pull request merged**
