### PR TITLE
Fixed OOB read in ntfs_make_data_run

### PR DESCRIPTION
**Pull request by joachimmetz**

### CODE REVIEW

**Comment by joachimmetz** [comment]
@APriestman what is the status of this review, the issue still persist in 4.11.0 and I've added some additional fixes to this PR related to more OOB read issues in the same code path

**Comment by rcordovano** [comment]
@joachimmetz, @APriestman has passed this PR, along with #2417 and #2434, on to @bcarrier for further review with the following remark: "PRs that add a maximum to different values. My guess is that these are probably fine."

**Comment by joachimmetz** [comment]
@rcordovano thx for the update

**Comment by joachimmetz** [comment]
@rcordovano what is the status of this PR? just added an additional check based on https://github.com/sleuthkit/sleuthkit/pull/2648

**Review by APriestman — APPROVED** [review]

**Pull request merged**
