### PR TITLE
Fix more compiler warnings

### PR DESCRIPTION
**Pull request by uckelman-sf**
This PR fixes some additional compiler warnings.

### CODE REVIEW

**Comment by bcarrier** [comment]
These may have conflicts with ones that I made in #1227...

**Comment by uckelman-sf** [comment]
It's possible. How would you like to resolve that?

**Comment by uckelman-sf** [comment]
It looks like there are some commits on the release-4.6.1 branch which aren't on develop. It would help me to resolve the conflicts if develop pulled in release-4.6.1.

**Comment by uckelman-sf** [comment]
Giving up on this one. Will make another PR.

**Pull request closed without merging**
