### PR TITLE
AFF4 support

### PR DESCRIPTION
**Pull request by uckelman-sf**
This PR adds support for AFF4 images to Sleuthkit.

This is a patch of PR #847 which fixes filename encoding for Windows, populates `TSK_IMG_INFO::images` without leaking memory, and centralizes cleanup after failure to open an image.

### CODE REVIEW

**Comment by blschatz** [comment]
Nicely done. Thanks!

**Comment by jonstewart** [comment]
*bump*

**Comment by blschatz** [comment]
bump++

**Review by APriestman — APPROVED** [review]

**Comment by uckelman-sf** [comment]
I've fixed the conflict. Could we get this merged, please?

**Comment by APriestman** [comment]
Can you give instructions on getting the aff4 library installed on linux? I tried a while back but had no luck (I'm not a linux person though so I may be missing something obvious). We don't want to take it until someone here has verified it works and we can add instructions on installing aff4 to the readme

**Comment by uckelman-sf** [comment]
Fixed conflict again.

**Comment by uckelman-sf** [comment]
@APriestman What have you 

> Can you give instructions on getting the aff4 library installed on linux? I tried a while back but had no luck (I'm not a linux person though so I may be missing something obvious).

I would need more information about what you tried and how it failed to be able to advise. There's no special configuration for libaff4 in the dynamically-linked stack we build:
```
./configure
make
make install
```
Can you show me what happens when you try that?

**Comment by APriestman** [comment]
How did you get the library?

**Comment by uckelman-sf** [comment]
It's here: https://github.com/Velocidex/c-aff4

**Comment by uckelman-sf** [comment]
Fixed conflict again.

**Comment by APriestman** [comment]
> It's here: https://github.com/Velocidex/c-aff4

Thanks. The error I get is:
../aff4/rdf.h:20:10: fatal error: spdlog/fmt/ostr.h: No such file or directory
20 | #include <spdlog/fmt/ostr.h>

It seems like the issue is that spdlog doesn't bundle fmt, but I don't understand how to fix it.

**Comment by uckelman-sf** [comment]
> > It's here: https://github.com/Velocidex/c-aff4
> 
> Thanks. The error I get is:
> ../aff4/rdf.h:20:10: fatal error: spdlog/fmt/ostr.h: No such file or directory
> 20 | #include <spdlog/fmt/ostr.h>
> 
> It seems like the issue is that spdlog doesn't bundle fmt, but I don't understand how to fix it.

I have `spdlog/fmt/ostr.h` in spdlog 0.17.0. It also seems to be present in 1.5.0, which is the system version I have here. What version are you using?

**Comment by uckelman-sf** [comment]
> PRIuOFF has been removed since 4.7.0

I've fixed that.

**Comment by uckelman-sf** [comment]
@mnrkbys I've added some additional commits to deal with the c-aff4 API change, among other things.

**Comment by tufelkinder** [comment]
Is this ever going to be available in Autopsy...?

**Comment by uckelman-sf** [comment]
Fixed conflicts.

**Comment by simsong** [comment]
great. This is still marked as draft?

**Comment by uckelman-sf** [comment]
@simsong It's still a draft because it cannot be merged before https://github.com/sleuthkit/sleuthkit/pull/2489. Will you have a look at that one, please?

**Comment by uckelman-sf** [comment]
@simsong Ready for review.

NB: I would like to add an `image.aff4` test image converted from `tests/data/img/image.dd`, but I have no way of doing that myself. If someone could produce that, I'd appreciate it.

**Comment by betty2310** [comment]
@uckelman-sf Hi, I have a question. What tool did you use for create aff4 image? Tks

**Comment by simsong** [comment]
Is it in the aff4 image metadata?

**Comment by uckelman-sf** [comment]
> @uckelman-sf Hi, I have a question. What tool did you use for create aff4 image? Tks

I did not. I've never been able to create an aff4 image myself.

**Comment by betty2310** [comment]
@uckelman-sf I've patched the library to support AFF4. Homever, when I try to use `fls` to list files from the aff4 image (created by using this tool in [here](https://github.com/Velocidex/c-aff4/releases)), I encounter the following error: 

```sh
fls -i aff4 /tmp/output.aff4
[1]    117445 floating point exception  sudo fls -i aff4 /tmp/output.aff4
```

But I even don't know the image output from this tool is correct, so may I ask you about another way to confirm the image is valid, and a sample aff4 image you used for testing?

**Comment by simsong** [comment]
> @uckelman-sf I've patched the library to support AFF4. Homever, when I try to use `fls` to list files from the aff4 image (created by using this tool in [here](https://github.com/Velocidex/c-aff4/releases)), I encounter the following error:
> 
> ```shell
> fls -i aff4 /tmp/output.aff4
> [1]    117445 floating point exception  sudo fls -i aff4 /tmp/output.aff4
> ```
> 
> But I even don't know the image output from this tool is correct, so may I ask you about another way to confirm the image is valid, and a sample aff4 image you used for testing?

This seems like an AFF4 library problem.  Do you have a way to validate your library and your image?

I thought that TSK supported AFF4 natively. How did you need to patch it?

**Comment by betty2310** [comment]
> > @uckelman-sf I've patched the library to support AFF4. Homever, when I try to use `fls` to list files from the aff4 image (created by using this tool in [here](https://github.com/Velocidex/c-aff4/releases)), I encounter the following error:
> > ```shell
> > fls -i aff4 /tmp/output.aff4
> > [1]    117445 floating point exception  sudo fls -i aff4 /tmp/output.aff4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I even don't know the image output from this tool is correct, so may I ask you about another way to confirm the image is valid, and a sample aff4 image you used for testing?
> 
> This seems like an AFF4 library problem. Do you have a way to validate your library and your image?
> 
> I thought that TSK supported AFF4 natively. How did you need to patch it?

The TSK doesn't support AFF4 natively. When running ./configure from the source code, I get:
```sh
 libaff4 support:                       no
```
So, I install the libaff4 from [here](https://github.com/Velocidex/c-aff4) as @uckelman-sf mentioned above. After installation, TSK appears to recognize AFF4 support.

> Do you have a way to validate your library and your image?

I have no idea to validate this library, for the image, I create by use this [tool](https://docs.aff4.org/en/latest/).

**Comment by betty2310** [comment]
@uckelman-sf Hi, use `fls` with aff4 image I get from the [ReferenceImages](https://github.com/aff4/ReferenceImages/tree/master/AFF4Std) repo. Seem like the error still occur

```sh
fls -i aff4 ~/ReferenceImages/AFF4Std/Base-Linear.aff4

[1]    166102 floating point exception  fls -i aff4 ~/ReferenceImages/AFF4Std/Base-Linear.aff4
```

**Comment by uckelman-sf** [comment]
There is nothing I can do without a test image or a way to create one. Please provide one of those if you want my help on this.

**Comment by simsong** [comment]
Let's migrate this discussion to #3156 
I never should have accepted this without a test image and test coverage. 
Lesson learned

**Pull request merged**
