### PR TITLE
Btrfs support

### PR DESCRIPTION
**Pull request by basicmaster**
As part of a practical course at my university, I developed Btrfs support for TSK and would like to contribute it. There are some restrictions of the support which I mentioned in the commit message.

I already did a rough indent to the code and hope it is enough.
Regarding my design decisions I already wrote some kind of implementation notes which I then will add to the wiki. The notes are ATM in German but I will translate them into English.
Soon I will also post a link to a Btrfs test image here.

### CODE REVIEW

**Comment by basicmaster** [comment]
I uploaded a test image: http://basicmaster.de/btrfs/btrfs_testimage_50MB.xz

Its `ls` output is shown [here](http://basicmaster.de/btrfs/btrfs_testimage_50MB_content.png). It contains at least one instance of every possible file type (except sockets).
The snapshot *snapshot* contains everything under `/` except the `after_snap_*` files.
There is also a deleted MP4 file being still in use which can be recovered via $OrphanFiles.

**Comment by simsong** [comment]
Is this still relevant?

**Comment by simsong** [comment]
Hi. Please rebase, resolve conflicts, and make sure it passes all check. Thanks.

**Comment by simsong** [comment]
> I uploaded a test image: http://basicmaster.de/btrfs/btrfs_testimage_50MB.xz
> 
> Its `ls` output is shown [here](http://basicmaster.de/btrfs/btrfs_testimage_50MB_content.png). It contains at least one instance of every possible file type (except sockets). The snapshot _snapshot_ contains everything under `/` except the `after_snap_*` files. There is also a deleted MP4 file being still in use which can be recovered via `$OrphanFiles`.

The test images have been copied to: https://corp.digitalcorpora.org/corpora/drives/2015-basicmaster/
* https://digitalcorpora.s3.amazonaws.com/corpora/drives/2015-basicmaster/btrfs_testimage_50MB.E01
* https://digitalcorpora.s3.amazonaws.com/corpora/drives/2015-basicmaster/btrfs_testimage_50MB.png
*

**Comment by simsong** [comment]
@basicmaster - are you interested in resolving the conflicts with your btrfs implementation?

**Comment by basicmaster** [comment]
I'll have to check how much effort is needed to adjust the MR to the TSK version...I will come back to you in a few days.

**Comment by simsong** [comment]
Thanks! I am sorry for the long delay on this.

**Comment by simsong** [comment]
We would love to have your notes in German.

**Comment by simsong** [comment]
I've moved this over to https://github.com/sleuthkit/sleuthkit/pull/3065 where I can work on it.

**Pull request closed without merging**
