### PR TITLE
Changed disable-java to enable-java #3029

### PR DESCRIPTION
**Pull request by joachimmetz**

### CODE REVIEW

**Comment by uckelman-sf** [comment]
When building with `--enable-java`, it's correct to abort when `javac` isn't available.

**Comment by simsong** [comment]
@joachimmetz  - are you okay with this?

**Comment by joachimmetz** [comment]
> When building with --enable-java, it's correct to abort when javac isn't available. What is this change intended to do?

there is no `--enable-java` option at the moment, it is implicitly assumed that JNI/Java support should be built. This PR changes configure to not abort if there is no javac

having a `--enable-java` (maybe `--enable-jni` would be better to disambiguate with SleuthKit Java framework)

**Comment by uckelman-sf** [comment]
> there is no --enable-java option at the moment, it is implicitly assumed that JNI/Java support should be built.

I don't understand on what basis you're saying this. From what I can see, the option is defined in `configure.ac`:
```
AC_ARG_ENABLE([java],
    [AS_HELP_STRING([--disable-java], [Do not build the java bindings or jar file])])
```

**Comment by joachimmetz** [comment]
```
./configure --help | grep java
  --disable-java          Do not build the java bindings or jar file
```

This is currently an implicit option

**Comment by uckelman-sf** [comment]
What do you mean by "implicit option"?

**Comment by joachimmetz** [comment]
that is not specifically called out in the help

**Comment by uckelman-sf** [comment]
Whether the option appears in the help doesn't affect the behavior of the option.

**Comment by joachimmetz** [comment]
> Whether the option appears in the help doesn't affect the behavior of the option.

it is currently implicitly enabled, why? this makes things unnecessary convoluted for people not wanting to build the JNI bindings

**Comment by joachimmetz** [comment]
> Would you state clearly what this PR is intended to do?

The PR does exactly say what it does, it prevents configure to abort if javac is not installed

**Comment by uckelman-sf** [comment]
I'm not in favor of the change as stated. I'm not convinced the PR does what it says it does yet.

**Comment by joachimmetz** [comment]
> I'm not in favor of the change as stated. I'm not convinced the PR does what it says it does yet.

why are you thinking this?

**Comment by uckelman-sf** [comment]
I have time at the moment only to address one part of that: I don't think the user should be forced to specify `--disable-java`. The Java build should be disabled by default.

I'll return to the rest later.

**Comment by joachimmetz** [comment]
>  I don't think the user should be forced to specify --disable-java. The Java build should be disabled by default.

then I'm happy to change the PR to match that

**Comment by uckelman-sf** [comment]
Wouldn't these changes be sufficient to make no Java the default?
```diff --git a/configure.ac b/configure.ac
index fe0870c83..b87cc32e3 100644
--- a/configure.ac
+++ b/configure.ac
@@ -84,7 +84,7 @@ AS_IF([test "x$ax_pthread_ok" = "xyes" && test "x$enable_multithreading" != "xno
 
 dnl Add enable/disable option
 AC_ARG_ENABLE([java],
-    [AS_HELP_STRING([--disable-java], [Do not build the java bindings or jar file])])
+    [AS_HELP_STRING([--enable-java], [Build the java bindings or jar file])])
 
 dnl Checks for libraries.
 
@@ -196,7 +196,7 @@ AM_COND_IF([CUSTOM_DEFAULT_JAR_LOCATION],
 )
 
 dnl Test for the various java things that we need for bindings
-AS_IF([test "x$enable_java" != "xno"], [
+AS_IF([test "x$enable_java" = "xyes"], [
     dnl javac is needed to compile the JAR file
     AX_PROG_JAVAC
     if test "x$JAVAC" != x; then
```

**Comment by joachimmetz** [comment]
`if test "x$JAVAC" != x; then` would likely have to be changed to use autoconf macros as well

**Comment by uckelman-sf** [comment]
I've had a chance to read through the changes now. I wouldn't bother with defining `AX_COMMON_ARG_DISABLE`, and would change the test as I mentioned above; otherwise, this seems fine.

**Comment by joachimmetz** [comment]
@uckelman-sf changes update, PTAL

**Comment by joachimmetz** [comment]
> I've had a chance to read through the changes now. I wouldn't bother with defining AX_COMMON_ARG_DISABLE, and would change the test as I mentioned above; otherwise, this seems fine.

the problem is that AC_ARG_ENABLE does not handle caching of options, but this is something for a different PR

**Review by simsong — APPROVED** [review]

**Comment by bcarrier** [comment]
So to confirm, the intended new behavior is that you need to opt-in for Java support? Even if all of the libraries exist, you need to supply 'enable-java'? 

If so, this seems inconsistent. Is the plan to also have people opt-in for libewf, afflib, etc. Isn't the whole point of autoconf that it detects what's there and includes it? 

If this is the intended behavior, it also requires documentation changes since it is a backward incompatible change.

**Comment by bcarrier** [comment]
100% agreed. Was configure failing though because javac wasn't detected? That's a bug in the macros and configure.ac if it was. Was it failing before all of the recent changes? I saw a bunch of that stuff moved around. 

At this point, I don't really care which way it goes.  We just need to update our build systems to start using this branch.

**Comment by joachimmetz** [comment]
@bcarrier this is the original issue https://github.com/sleuthkit/sleuthkit/issues/3029#issuecomment-2408418288  from the sound of it you would favor the original proposal of disabling java when no javac and enabling when all requirements are met. 

> What I objected to originally was configure failing when javac wasn't detected and --enable-java wasn't specified. In that situation, you should get a build with Java disabled because you don't have what's required for building with it---as you say.

no you did not you did the opposite, the original proposal was to no fail if javac was not available. The TSK behavior at that time was to fail per https://github.com/sleuthkit/sleuthkit/issues/3029

**Comment by uckelman** [comment]
What should happen is:

* `configure` should give an error if `--enable-java` is given but the requirements aren't met
* `configure` should not build anything with Java if `--disable-java` is given.
* `configure` should not build anything with Java if neither option is specified and the requirements for building with Java aren't met

Regarding configure defaults: It's not unusual for projects to have an assortment of defaults, some enabled, some detected, and some disabled, depending on how likely users are to want them. If Joachim wants that changed, he could make another PR for it, I suppose.

**Comment by joachimmetz** [comment]
> That's not controversial, I think?

sigh you still don't get it do you? in https://github.com/sleuthkit/sleuthkit/issues/3029#issuecomment-2408418288 i flagged that the behavior you claim "should happen" did not happen. My guess it that https://github.com/sleuthkit/sleuthkit/commit/bbad55df332bce3a37ff6cf785361792a631df2e introduced the issue that the build fails when there is no javac

My initial changes were to have "configure should not build anything with Java if neither option is specified and the requirements for building with Java aren't met"

**Pull request merged**
