### PR TITLE
Add support for LZVN-compressed files on HFS+

### PR DESCRIPTION
**Pull request by uckelman-sf**
This PR adds support for LZVN-compressed files on HFS+ filesystems.

### CODE REVIEW

**Comment by bcarrier** [comment]
We're going to get this tested and integrated for the Oct 1 release.

**Comment by sf-jonstewart** [comment]
Great. We do Windows builds with mingw on Linux, so it's great to see integration of AppVeyor for testing VisualStudio builds. Looks like it shouldn't be too hard to get these things passing. @uckelman-sf, can you fix up the couple of issues identified above (linker error with VS on a wide-string function and a silly for-loop thing in lzvn.c)?

**Comment by uckelman-sf** [comment]
I've fixed the two issues @sf-jonstewart noted above.

W/r/t the for-loop issue: It would be nice if we were compiling at least under the C99 standard. Is there any interest in updating the codebase for compiling with `-std=c99` in `CFLAGS`? I'd be willing to do that (on a different branch).

**Comment by bcarrier** [comment]
Thanks.  Just noticed this was directed to the 4.4.2 branch. Can you redirect to develop?

**Comment by uckelman-sf** [comment]
Base branch changed to develop.

**Comment by sf-jonstewart** [comment]
woot

**Comment by bcarrier** [comment]
@uckelman-sf and @sf-jonstewart .  Thanks for the PR.  At some point though can you add some method-level comments to the new compression code about what it does, arguments, and return values?  Also there are some new warnings (and I'm trying to clean up all of the warnings that built up over time):

1>  lzvn.c
1>..\..\tsk\fs\lzvn.c(532): warning C4018: '>': signed/unsigned mismatch
1>..\..\tsk\fs\lzvn.c(228): warning C4102: 'sml_d': unreferenced label
1>..\..\tsk\fs\lzvn.c(371): warning C4102: 'med_d': unreferenced label
1>..\..\tsk\fs\lzvn.c(421): warning C4102: 'lrg_d': unreferenced label
1>..\..\tsk\fs\lzvn.c(457): warning C4102: 'pre_d': unreferenced label
1>..\..\tsk\fs\lzvn.c(595): warning C4102: 'sml_m': unreferenced label
1>..\..\tsk\fs\lzvn.c(624): warning C4102: 'lrg_m': unreferenced label
1>..\..\tsk\fs\lzvn.c(646): warning C4102: 'sml_l': unreferenced label
1>..\..\tsk\fs\lzvn.c(671): warning C4102: 'lrg_l': unreferenced label
1>..\..\tsk\fs\lzvn.c(739): warning C4102: 'nop': unreferenced label
1>..\..\tsk\fs\lzvn.c(756): warning C4102: 'eos': unreferenced label
1>..\..\tsk\fs\lzvn.c(771): warning C4102: 'udef': unreferenced label

and some size ones in hfs.c

thanks.

**Comment by uckelman-sf** [comment]
@bcarrier, what warnings do you get from hfs.c? The only one I get when compiling with gcc, mingw32, or mingw64 is this one:
```
hfs.c:1312:1: warning: 'hfs_lookup_hard_link' defined but not used [-Wunused-function]
 hfs_lookup_hard_link(HFS_INFO * hfs, TSK_INUM_T linknum,
 ^~~~~~~~~~~~~~~~~~~~
```

**Comment by uckelman-sf** [comment]
Hang on, I see that your autotools setup isn't compiling with `-Wextra -Wpedanitc`. I do get some warnings from hfs.c with those.

**Comment by uckelman-sf** [comment]
@bcarrier PR 985 fixes the warnings, add documentation, and fixes a minor bug.

**Pull request merged**
