### PR TITLE
Added OSS-Fuzz fuzz targets #2429

### PR DESCRIPTION
**Pull request by joachimmetz**
This PR incorporates files that were copied from https://github.com/google/oss-fuzz/tree/80d39ec418fda8ea9ee6e3e91d7d9341affaf421/projects/sleuthkit under Apache License 2

### CODE REVIEW

**Comment by joachimmetz** [comment]
@bcarrier @rcordovano what is the status of the review of this PR ?

**Comment by joachimmetz** [comment]
@gdicristofaro any questions / updates?

**Comment by joachimmetz** [comment]
@simsong if you're looking at changes to improve CI and testing, PTAL

**Comment by simsong** [comment]
We've moved to a single Makefile, because 'recursive make is considered harmful.' But if you want to keep this as a different makefile, I'm okay with that.

**Comment by joachimmetz** [comment]
> We've moved to a single Makefile, because 'recursive make is considered harmful.' 

Any additional context what is "harmful" about it?

> But if you want to keep this as a different makefile, I'm okay with that.

I've rebased the PR, kept the separate Makefile.am for now, but can move it into the main one

**Comment by simsong** [comment]
> > We've moved to a single Makefile, because 'recursive make is considered harmful.'
> 
> Any additional context what is "harmful" about it?

Yes!

https://accu.org/journals/overload/14/71/miller_2004/

**Comment by joachimmetz** [comment]
> https://accu.org/journals/overload/14/71/miller_2004/

thanks I'll take a closer read, but at first glance looks like this is specifically about "vanilla make" not about make in combination with autotools

**Comment by simsong** [comment]
It is specifically about auto tools! We used it for years at sandstorm as a
guiding principle.

**Comment by joachimmetz** [comment]
> It is specifically about auto tools! 

I might be missing the point then, given technically there is nothing preventing automake from generating a single Makefile.

**Comment by simsong** [comment]
That’s what we are doing!

**Comment by joachimmetz** [comment]
> That’s what we are doing!

I meant more as automake generating a single Makefile based on recursive Makefile.am configuration.

the automake link I added gave me a bit more context from the autotools perspective what are the tradeoffs.

Let me know if the ossfuzz Makefile.am should be moved into the main Makefile.am given it's specific use case might not be providing a lot of benefit

**Comment by simsong** [comment]
Ah. Yes. We would prefer it to be in the root Makefile.am.

**Comment by joachimmetz** [comment]
I'll take a look tomorrow, to move it, should not be too involved.

**Comment by joachimmetz** [comment]
@simsong PTAL, moved ossfuzz/Makefile.am into Makefile.am and added a CI test to test the ossfuzz build

**Review by simsong — APPROVED** [review]
Thanks for the fuzzer!

**Pull request merged**
