### PR TITLE
Move bundled sqlite3 to vendors

### PR DESCRIPTION
**Pull request by uckelman-sf**
This PR moves the bundled sqlite3 to `vendors/`, where it should be because it's not our code.

### CODE REVIEW

**Comment by uckelman-sf** [comment]
@simsong Ready for review.

**Review by simsong — APPROVED** [review]
`/vendors/` is fine, but I probably would have gone with `/3rdparty/`...

**Comment by uckelman** [comment]
`vendors/` is used fairly widely. I've never seen `3rdparty/` in a project before.

**Comment by simsong** [comment]
I defer to you!

**Pull request merged**
